[2025-05-21T14:11:28.311+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-21T14:11:28.333+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: macro_trading_dag.fetch_fred_data manual__2025-05-21T12:11:25.538932+00:00 [queued]>
[2025-05-21T14:11:28.340+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: macro_trading_dag.fetch_fred_data manual__2025-05-21T12:11:25.538932+00:00 [queued]>
[2025-05-21T14:11:28.341+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2025-05-21T14:11:28.366+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_fred_data> on 2025-05-21 12:11:25.538932+00:00
[2025-05-21T14:11:28.370+0200] {standard_task_runner.py:63} INFO - Started process 317724 to run task
[2025-05-21T14:11:28.373+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'macro_trading_dag', 'fetch_fred_data', 'manual__2025-05-21T12:11:25.538932+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpc1eent1u']
[2025-05-21T14:11:28.374+0200] {standard_task_runner.py:91} INFO - Job 41: Subtask fetch_fred_data
[2025-05-21T14:11:28.447+0200] {task_command.py:426} INFO - Running <TaskInstance: macro_trading_dag.fetch_fred_data manual__2025-05-21T12:11:25.538932+00:00 [running]> on host N15I711-16GR512.
[2025-05-21T14:11:28.531+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='leoja' AIRFLOW_CTX_DAG_ID='macro_trading_dag' AIRFLOW_CTX_TASK_ID='fetch_fred_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T12:11:25.538932+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T12:11:25.538932+00:00'
[2025-05-21T14:11:28.541+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-21T14:11:28.555+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-21T14:11:28.556+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow/dags/my_first_dag.py", line 36, in fetch_fred_data
    existing_data = pd.read_csv(FINAL_CSV, index_col='DATE', parse_dates=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2025-05-21T14:11:28.574+0200] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=macro_trading_dag, task_id=fetch_fred_data, execution_date=20250521T121125, start_date=20250521T121128, end_date=20250521T121128
[2025-05-21T14:11:28.600+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 41 for task fetch_fred_data (No columns to parse from file; 317724)
[2025-05-21T14:11:28.628+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-21T14:11:28.644+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-21T14:11:28.644+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
