[2025-05-20T23:50:07.741+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-20T23:50:07.753+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: macro_trading_dag.fetch_fred_data manual__2025-05-20T21:45:02.788725+00:00 [queued]>
[2025-05-20T23:50:07.756+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: macro_trading_dag.fetch_fred_data manual__2025-05-20T21:45:02.788725+00:00 [queued]>
[2025-05-20T23:50:07.757+0200] {taskinstance.py:2303} INFO - Starting attempt 2 of 4
[2025-05-20T23:50:07.772+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_fred_data> on 2025-05-20 21:45:02.788725+00:00
[2025-05-20T23:50:07.775+0200] {standard_task_runner.py:63} INFO - Started process 273561 to run task
[2025-05-20T23:50:07.778+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'macro_trading_dag', 'fetch_fred_data', 'manual__2025-05-20T21:45:02.788725+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp3lfu0j0f']
[2025-05-20T23:50:07.778+0200] {standard_task_runner.py:91} INFO - Job 13: Subtask fetch_fred_data
[2025-05-20T23:50:07.815+0200] {task_command.py:426} INFO - Running <TaskInstance: macro_trading_dag.fetch_fred_data manual__2025-05-20T21:45:02.788725+00:00 [running]> on host N15I711-16GR512.
[2025-05-20T23:50:07.855+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='leoja' AIRFLOW_CTX_DAG_ID='macro_trading_dag' AIRFLOW_CTX_TASK_ID='fetch_fred_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T21:45:02.788725+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T21:45:02.788725+00:00'
[2025-05-20T23:50:07.856+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-20T23:50:07.857+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-20T23:50:07.857+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow/dags/my_first_dag.py", line 32, in fetch_fred_data
    data = fred.FredReader(series=list(fred_series.values()),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _BaseReader.__init__() got an unexpected keyword argument 'series'
[2025-05-20T23:50:07.860+0200] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=macro_trading_dag, task_id=fetch_fred_data, execution_date=20250520T214502, start_date=20250520T215007, end_date=20250520T215007
[2025-05-20T23:50:07.871+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task fetch_fred_data (_BaseReader.__init__() got an unexpected keyword argument 'series'; 273561)
[2025-05-20T23:50:07.911+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-20T23:50:07.926+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T23:50:07.927+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
