[2025-05-20T23:43:12.395+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-20T23:43:12.418+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: macro_trading_dag.fetch_fred_data scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T23:43:12.424+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: macro_trading_dag.fetch_fred_data scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T23:43:12.424+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2025-05-20T23:43:12.439+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_fred_data> on 2025-05-19 00:00:00+00:00
[2025-05-20T23:43:12.443+0200] {standard_task_runner.py:63} INFO - Started process 271868 to run task
[2025-05-20T23:43:12.448+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'macro_trading_dag', 'fetch_fred_data', 'scheduled__2025-05-19T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpl8il13hp']
[2025-05-20T23:43:12.449+0200] {standard_task_runner.py:91} INFO - Job 3: Subtask fetch_fred_data
[2025-05-20T23:43:12.531+0200] {task_command.py:426} INFO - Running <TaskInstance: macro_trading_dag.fetch_fred_data scheduled__2025-05-19T00:00:00+00:00 [running]> on host N15I711-16GR512.
[2025-05-20T23:43:12.604+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='leoja' AIRFLOW_CTX_DAG_ID='macro_trading_dag' AIRFLOW_CTX_TASK_ID='fetch_fred_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T00:00:00+00:00'
[2025-05-20T23:43:12.605+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-20T23:43:12.607+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-20T23:43:12.607+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow_venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/leoja/airflow/dags/my_first_dag.py", line 35, in fetch_fred_data
    data = fred.FredReader(series=list(fred_series.values()),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _BaseReader.__init__() got an unexpected keyword argument 'series'
[2025-05-20T23:43:12.615+0200] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=macro_trading_dag, task_id=fetch_fred_data, execution_date=20250519T000000, start_date=20250520T214312, end_date=20250520T214312
[2025-05-20T23:43:12.627+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task fetch_fred_data (_BaseReader.__init__() got an unexpected keyword argument 'series'; 271868)
[2025-05-20T23:43:12.661+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-20T23:43:12.677+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T23:43:12.678+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
